// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCol: typeof import('element-plus/es')['ElCol'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    SvgIcon: typeof import('./../src/components/SvgIcon.vue')['default'];
  }
}

export {};
